name: Run Cartoonify OpenCV

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4  # Nâng cấp lên v4

    - name: Set up Python
      uses: actions/setup-python@v5  # Nâng cấp lên v5
      with:
        python-version: '3.10'

    - name: Install OpenCV Headless
      run: pip install opencv-python-headless

    - name: Download Sample Image
      run: |
        wget https://raw.githubusercontent.com/opencv/opencv/master/samples/data/lena.jpg -O input.jpg

    - name: Run Cartoonify Script
      run: python cartoon.py input.jpg output_cartoon.jpg

    - name: Upload Cartoon Image as Artifact
      uses: actions/upload-artifact@v4  # Nâng cấp lên v4 để khắc phục lỗi
      with:
        name: cartoon-result
        path: output_cartoon.jpg
